### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mplodowski** [suresoftware/october-mail-log#10]
Hi,

great plugin!

I have one issue with plugin permissions. Plugin does not register his own permissions, so I assume you would like to use October logs default.

Currently this is set to:

https://github.com/suresoftware/october-mail-log/blob/fd985925c174e2c13455567b5084b0b6655afce7/controllers/MailLogs.php#L20

but the correct value should be `system.access_logs`.

**Comment by Humni** [comment]
@mplodowski thanks for this! Yes I'm not sure how that issue slipped past me, I'll get this merged right away :)
