### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by chrisvidal** [suresoftware/october-mail-log#13]
Could you please update the plugin so that we can install it through the backend OC472

![image](https://user-images.githubusercontent.com/2263496/117750034-55637100-b245-11eb-907e-97677cbef705.png)

**Comment by Humni** [comment]
@chrisvidal you're adding it incorrectly. It's "SureSoftware.Maillog" - it should also auto complete when you search mail log.

**Comment by chrisvidal** [comment]
well, this is coming direclty from the marketplace, I didn't add anything

**Comment by Humni** [comment]
@chrisvidal Mja.Mail isn't even the name of this package
