### ISSUE TITLE
[Feature] Purge the log older than X days

### ISSUE THREAD

**Issue by pvullioud** [suresoftware/october-mail-log#3]
- Add a setting to define a number days to keep the logs  (0 == no purge)
- Add a command
- Schedule the command each day

What do you think to add a cog icon in the list to access this setting instead of creating a new entry in the settings menu

Have a great week-end

**Comment by Humni** [comment]
@pvullioud this sounds like a good idea - otherwise, the plugin can have issues in regards to GDPR and also fill up the DB over time if you're sending lots of emails. 

Are you able to create a PR for this?

**Comment by pvullioud** [comment]
Yes, I'll code it.
I work at the same place than @ChVuagniaux https://inetis.ch/agence-web
Greetings from Switzerland

**Comment by Humni** [comment]
@pvullioud thank you! I look forward to reviewing it

Kia ora from New Zealand
