### ISSUE TITLE
Fix for count error when there are no attachments

### ISSUE THREAD

**Issue by Dahfrenk** [suresoftware/october-mail-log#4]
In the model change the getAttachmentsCountAttribute function to the following
`
if (isset($this->attachments))
{
   return count($this->attachments);
}`

**Comment by SplicedWeb** [comment]
I solved this error "count(): Parameter must be an array or an object that implements Countable"
/plugins/suresoftware/maillog/models/MailLog.php line 63  
`
public function getAttachmentsCountAttribute()
    {
        if ($this->attachments === null || $this->attachments === 0) {
             return 0;
        } else {
              return count($this->attachments);
        }
    }
`
Created a pull request.

**Comment by Humni** [comment]
Resolved in #5
