### ISSUE TITLE
Access Denied Error Page after installing and trying to access Mail Log

### ISSUE THREAD

**Issue by max-auw** [suresoftware/october-mail-log#7]
![image](https://user-images.githubusercontent.com/57607815/82417624-66542900-9aae-11ea-8db3-786ec009804e.png)

Any advice?

**Comment by Humni** [comment]
@max-auw  did you setup the mail log permissions correctly and are you logged in?

There is not enough information on this ticket as the plugin works for superuser accounts out of the box without any setup or configuration required.
